[global]
background = "#332720"
foreground = "#F4E7DA"
frame_color = "#DDA15E"
separator_color = "#DDA15E"
corner_radius = 14
frame_width = 2
offset = 16x16
gap_size = 10
transparency = 0

[urgency_low]
background = "#3A2B24"
foreground = "#EADBCD"
frame_color = "#C39A76"
highlight = "#C39A76"

[urgency_normal]
background = "#45342B"
foreground = "#F4E7DA"
frame_color = "#DDA15E"
highlight = "#E9C46A"

[urgency_critical]
background = "#5A3E31"
foreground = "#FFF5EC"
frame_color = "#B66A50"
highlight = "#B66A50"
