# Screenshots
# SUPER + ,  -> select area
# SUPER + .  -> active window
# SUPER + -  -> fullscreen
bind = SUPER, comma, exec, ~/.local/bin/polarshot area
bind = SUPER, period, exec, ~/.local/bin/polarshot active
bind = SUPER, minus, exec, ~/.local/bin/polarshot full
