[global]
background = "#2A2038"
foreground = "#F5E0DC"
frame_color = "#F5C2E7"
separator_color = "#F5C2E7"
corner_radius = 16
frame_width = 3
offset = 18x18
gap_size = 12
transparency = 0

[urgency_low]
background = "#31243F"
foreground = "#EBDCF7"
frame_color = "#89B4FA"
highlight = "#89B4FA"

[urgency_normal]
background = "#3A274A"
foreground = "#F5E0DC"
frame_color = "#F5C2E7"
highlight = "#F5C2E7"

[urgency_critical]
background = "#4A2D4A"
foreground = "#FFE2EC"
frame_color = "#F38BA8"
highlight = "#F38BA8"
