[window]
dimensions = { columns = 120, lines = 32 }
padding = { x = 10, y = 10 }
dynamic_padding = true
opacity = 0.80

[scrolling]
history = 10000

[font]
normal = { family = "FiraCode Nerd Font Mono", style = "Regular" }
size = 11.0

[cursor]
style = { shape = "Block", blinking = "Never" }
vi_mode_style = { shape = "Block", blinking = "Never" }

[selection]
save_to_clipboard = true

[mouse]
hide_when_typing = true

[colors]
transparent_background_colors = false
draw_bold_text_with_bright_colors = false

[colors.primary]
background = "#24283b"
foreground = "#c0caf5"
dim_foreground = "#a9b1d6"

[colors.cursor]
text = "#24283b"
cursor = "#c0caf5"

[colors.vi_mode_cursor]
text = "#24283b"
cursor = "#c0caf5"

[colors.selection]
text = "CellForeground"
background = "#3b4261"

[colors.search]
matches = { foreground = "CellBackground", background = "#7dcfff" }
focused_match = { foreground = "CellBackground", background = "#7dcfff" }

[colors.footer_bar]
background = "#292e42"
foreground = "#c0caf5"

[colors.normal]
black = "#414868"
red = "#f7768e"
green = "#9ece6a"
yellow = "#e0af68"
blue = "#7aa2f7"
magenta = "#bb9af7"
cyan = "#7dcfff"
white = "#a9b1d6"

[colors.bright]
black = "#414868"
red = "#f7768e"
green = "#9ece6a"
yellow = "#e0af68"
blue = "#7aa2f7"
magenta = "#bb9af7"
cyan = "#7dcfff"
white = "#c0caf5"

[colors.dim]
black = "#1f2335"
red = "#b5585f"
green = "#73a857"
yellow = "#a58a4a"
blue = "#526598"
magenta = "#8c6c9e"
cyan = "#4fb3d8"
white = "#828bb8"

